# coding: utf-8

"""
    Description: python client
    Generated by: ecloud-sdk
"""

import sys

from typing import List

from ecloudsdkcore.config.config import Config
from ecloudsdkvpc.v1.model import *
from ecloudsdkvpc.v1.client import Client


class CreateSecurityRuleSample:
    def __init__(self):
        pass

    @staticmethod
    def create_client(access_key: str, access_secret: str, pool_id: str) -> Client:
        """
        使用AK&SK初始化账号Client
        @param access_key:
        @param access_secret:
        @param pool_id:
        @return: Client
        @throws Exception
        """
        config = Config(
            access_key=access_key, access_secret=access_secret, pool_id=pool_id
        )
        return Client(config)

    @staticmethod
    def main(args: List[str]) -> None:
        client = CreateSecurityRuleSample.create_client(
            "2KouFi1Q2j6nlzL0rDOERzwsiJp5",
            "b329t280pdDdZuNEuTV7oceXf3Abia",
            "CIDC-RP-25",
        )
        request = CreateSecurityRuleRequest()
        create_security_rule_body = CreateSecurityRuleBody()
        create_security_rule_body.security_group_id = (
            "2d64eeb1-d8f0-446a-92dc-79543fb7a027"
        )
        create_security_rule_body.remote_type = "cidr"
        create_security_rule_body.protocol = "TCP"
        create_security_rule_body.min_port_range = 22
        create_security_rule_body.ether_type = "IPv4"
        create_security_rule_body.remote_ip_prefix = "60.24.0.0/14"
        create_security_rule_body.direction = "ingress"
        create_security_rule_body.max_port_range = 22
        request.create_security_rule_body = create_security_rule_body
        client.create_security_rule(request)


if __name__ == "__main__":
    CreateSecurityRuleSample.main(sys.argv[1:])
